import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { ConfigModule, ConfigService } from '@nestjs/config';

import {
  AdminSetting, AdminSettingSchema,
  Availability, AvailabilitySchema,
  Banner, BannerSchema,
  Booking, BookingSchema,
  Chat, ChatSchema,
  ChatMessage, ChatMessageSchema,
  ChatRoom, ChatRoomSchema,
  ContactUs, ContactUsSchema,
  Coupon, CouponSchema,
  Faq, FaqSchema,
  Institution, InstitutionSchema,
  MasterService, MasterServiceSchema,
  Message, MessageSchema,
  Notification, NotificationSchema,
  Order, OrderSchema,
  Payment, PaymentSchema,
  Payout, PayoutSchema,
  Product, ProductSchema,
  Review, ReviewSchema,
  RideRequest, RideRequestSchema,
  StaticPages, StaticPagesSchema,
  SubCategory, SubCategorySchema,
  TempMobile, TempMobileSchema,
  Transaction, TransactionSchema,
  UsedItem, UsedItemSchema,
  UsedOffer, UsedOfferSchema,
  User, UserSchema,
  Vehicle, VehicleSchema,
  VehicleType, VehicleTypeSchema,
  Zone, ZoneSchema,
  SuperAdmin, SuperAdminSchema,
  EducationInquiry, EducationInquirySchema,
} from './schemas';

const mongooseFeatures = MongooseModule.forFeature([
  { name: AdminSetting.name, schema: AdminSettingSchema },
  { name: Availability.name, schema: AvailabilitySchema },
  { name: Banner.name, schema: BannerSchema },
  { name: Booking.name, schema: BookingSchema },
  { name: Chat.name, schema: ChatSchema },
  { name: ChatMessage.name, schema: ChatMessageSchema },
  { name: ChatRoom.name, schema: ChatRoomSchema },
  { name: ContactUs.name, schema: ContactUsSchema },
  { name: Coupon.name, schema: CouponSchema },
  { name: Faq.name, schema: FaqSchema },
  { name: Institution.name, schema: InstitutionSchema },
  { name: MasterService.name, schema: MasterServiceSchema },
  { name: Message.name, schema: MessageSchema },
  { name: Notification.name, schema: NotificationSchema },
  { name: Order.name, schema: OrderSchema },
  { name: Payment.name, schema: PaymentSchema },
  { name: Payout.name, schema: PayoutSchema },
  { name: Product.name, schema: ProductSchema },
  { name: Review.name, schema: ReviewSchema },
  { name: RideRequest.name, schema: RideRequestSchema },
  { name: StaticPages.name, schema: StaticPagesSchema },
  { name: SubCategory.name, schema: SubCategorySchema },
  { name: TempMobile.name, schema: TempMobileSchema },
  { name: Transaction.name, schema: TransactionSchema },
  { name: UsedItem.name, schema: UsedItemSchema },
  { name: UsedOffer.name, schema: UsedOfferSchema },
  { name: User.name, schema: UserSchema },
  { name: Vehicle.name, schema: VehicleSchema },
  { name: VehicleType.name, schema: VehicleTypeSchema },
  { name: Zone.name, schema: ZoneSchema },
  { name: SuperAdmin.name, schema: SuperAdminSchema },
  { name: EducationInquiry.name, schema: EducationInquirySchema },
]);

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    MongooseModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        uri: config.get<string>('MONGO_URI'),
      }),
    }),
    mongooseFeatures,
  ],
  exports: [mongooseFeatures],
})
export class DatabaseModule { }
